spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/epidemic?serverTimezone=CST"
    username: "root"
    password: "123456"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  messages:
    basename: "i18n.list"

  mail:
    username: "cing_self0731@qq.com"
    password: "gtcymduepuxeccif"
    host: "smtp.qq.com"
    properties.mail.smtp.ssl.enable: "true"